version: "3.9"

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Node JS api service
  api:
    build: .
    ports:
      - 3001:4000
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: MONGOOSE_ENVIRONMENT
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
